# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/pin_assignment/mb_usb_hdmi_top.xdc

# IP: ip/zero_rom/zero_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zero_rom || ORIG_REF_NAME==zero_rom} -quiet] -quiet

# Block Designs: bd/qiu/qiu.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qiu || ORIG_REF_NAME==qiu} -quiet] -quiet

# IP: bd/qiu/ip/qiu_microblaze_0_0/qiu_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qiu_microblaze_0_0 || ORIG_REF_NAME==qiu_microblaze_0_0} -quiet] -quiet

# IP: bd/qiu/ip/qiu_dlmb_v10_0/qiu_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qiu_dlmb_v10_0 || ORIG_REF_NAME==qiu_dlmb_v10_0} -quiet] -quiet

# IP: bd/qiu/ip/qiu_ilmb_v10_0/qiu_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qiu_ilmb_v10_0 || ORIG_REF_NAME==qiu_ilmb_v10_0} -quiet] -quiet

# IP: bd/qiu/ip/qiu_dlmb_bram_if_cntlr_0/qiu_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qiu_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==qiu_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/qiu/ip/qiu_ilmb_bram_if_cntlr_0/qiu_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qiu_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==qiu_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/qiu/ip/qiu_lmb_bram_0/qiu_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qiu_lmb_bram_0 || ORIG_REF_NAME==qiu_lmb_bram_0} -quiet] -quiet

# IP: bd/qiu/ip/qiu_xbar_0/qiu_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qiu_xbar_0 || ORIG_REF_NAME==qiu_xbar_0} -quiet] -quiet

# IP: bd/qiu/ip/qiu_microblaze_0_axi_periph_0/qiu_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qiu_microblaze_0_axi_periph_0 || ORIG_REF_NAME==qiu_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/qiu/ip/qiu_microblaze_0_axi_intc_0/qiu_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qiu_microblaze_0_axi_intc_0 || ORIG_REF_NAME==qiu_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/qiu/ip/qiu_microblaze_0_xlconcat_0/qiu_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qiu_microblaze_0_xlconcat_0 || ORIG_REF_NAME==qiu_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/qiu/ip/qiu_mdm_1_0/qiu_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qiu_mdm_1_0 || ORIG_REF_NAME==qiu_mdm_1_0} -quiet] -quiet

# IP: bd/qiu/ip/qiu_clk_wiz_1_0/qiu_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qiu_clk_wiz_1_0 || ORIG_REF_NAME==qiu_clk_wiz_1_0} -quiet] -quiet

# IP: bd/qiu/ip/qiu_rst_clk_wiz_1_100M_0/qiu_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qiu_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==qiu_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/qiu/ip/qiu_axi_gpio_0_0/qiu_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qiu_axi_gpio_0_0 || ORIG_REF_NAME==qiu_axi_gpio_0_0} -quiet] -quiet

# IP: bd/qiu/ip/qiu_axi_gpio_1_0/qiu_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qiu_axi_gpio_1_0 || ORIG_REF_NAME==qiu_axi_gpio_1_0} -quiet] -quiet

# IP: bd/qiu/ip/qiu_axi_gpio_2_0/qiu_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qiu_axi_gpio_2_0 || ORIG_REF_NAME==qiu_axi_gpio_2_0} -quiet] -quiet

# IP: bd/qiu/ip/qiu_axi_timer_0_0/qiu_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qiu_axi_timer_0_0 || ORIG_REF_NAME==qiu_axi_timer_0_0} -quiet] -quiet

# IP: bd/qiu/ip/qiu_axi_quad_spi_0_0/qiu_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qiu_axi_quad_spi_0_0 || ORIG_REF_NAME==qiu_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/qiu/ip/qiu_axi_uartlite_0_0/qiu_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qiu_axi_uartlite_0_0 || ORIG_REF_NAME==qiu_axi_uartlite_0_0} -quiet] -quiet

# XDC: u:/Downloads/ece385/final_project_111/final_project_1/final_project_1.gen/sources_1/bd/qiu/qiu_ooc.xdc
