# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: u:/Downloads/ece385/final_project_111/final_project_1/final_project_1.srcs/sources_1/ip/player2_3_rom/player2_3_rom.xci
# IP: The module: 'player2_3_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/Downloads/ece385/final_project_111/final_project_1/final_project_1.gen/sources_1/ip/player2_3_rom/player2_3_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'player2_3_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: u:/Downloads/ece385/final_project_111/final_project_1/final_project_1.srcs/sources_1/ip/player2_3_rom/player2_3_rom.xci
# IP: The module: 'player2_3_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/Downloads/ece385/final_project_111/final_project_1/final_project_1.gen/sources_1/ip/player2_3_rom/player2_3_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'player2_3_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
