# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: U:/Downloads/ece385/final_project_111/final_project_1/final_project_1.srcs/sources_1/ip/contra_people_2_1/contra_people_2_1.xci
# IP: The module: 'contra_people_2_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/Downloads/ece385/final_project_111/final_project_1/final_project_1.gen/sources_1/ip/contra_people_2_1/contra_people_2_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'contra_people_2_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: U:/Downloads/ece385/final_project_111/final_project_1/final_project_1.srcs/sources_1/ip/contra_people_2_1/contra_people_2_1.xci
# IP: The module: 'contra_people_2_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/Downloads/ece385/final_project_111/final_project_1/final_project_1.gen/sources_1/ip/contra_people_2_1/contra_people_2_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'contra_people_2_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
